name: Merge Dependabot PRs
on:
  pull_request:

jobs:
  automerge:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@v2
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: minor