name: 'Validate HACS'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - dev

jobs:
  validate:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - name: HACS validation
        uses: 'hacs/integration/action@master'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CATEGORY: 'plugin'
